### PR TITLE
TurtleShroom Productions Proudly Presents: Based Fungi Overhaul

### PR DESCRIPTION
**Pull request by TurtleShroom**
This Pull Request incorporates massive improvements and changes to the Fungi Mod, comprising a comprehensive and exciting experience for players, including compatibility for many, many Mods.

### CODE REVIEW

**Comment by emipa606** [comment]
Tried this and got the following errors when starting the game:

```
Exception parsing <li>HairStyle</li> to type Verse.EndogeneCategory: System.ArgumentException: Exception parsing Verse.EndogeneCategory from "HairStyle"
Exception parsing <li>BeardStyle</li> to type Verse.EndogeneCategory: System.ArgumentException: Exception parsing Verse.EndogeneCategory from "BeardStyle"
Exception parsing <li>Fur</li> to type Verse.EndogeneCategory: System.ArgumentException: Exception parsing Verse.EndogeneCategory from "Fur"
Could not resolve cross-reference to Verse.PawnKindDef named TSP_VFEF_FakeFungi (wanter=kindDefs)
```

**Comment by TurtleShroom** [comment]
I think I forgot to deploy the MAYREQUIRE system. I will check.
--
Sent from Mail.ru app for Android Sunday, 15 October 2023, 03:36PM -04:00 from Mlie  ***@***.*** :

**Comment by TurtleShroom** [comment]
> Tried this and got the following errors when starting the game
> ```

Okay, try now.

**Comment by emipa606** [comment]
Published in 510ecd7
Fixed the faulty ` Name="FungiMelee" ` in the TSP_FungiSlave def

**Pull request merged**
